---
title: "Visualizing Spatial Data Using Google Maps"
author: "Jack Bienvenue"
date: "09.18.2024"
format: 
    revealjs:
        theme: default
---
# Spatial Data

## What makes spatial data special?

- Geocoding
- Vector and Raster Operations

---

---

# Spatial Data Handling Platforms

## Platforms for processing/ visualizing spatial data:

- R
- Python
- ArcGIS
- Google
    - Google MyMaps
    - Google Maps
    - Google Earth Engine
---
# Working with Google Maps
---
## Preliminaries
A few notes before introducing visualization with Google Maps. 
---
### Google MyMaps
Google MyMaps is a tool that can help us visualize spatial data. Upload data to MyMaps by: 

1. Creating a .csv with all entries where geocodes are present
2. Uploading that to your Google Drive
3. Uploading from your drive on the MyMaps webpage

---
<div style="display: flex;">

<div style="flex: 1; padding: 10px;">
### Pros
- Ease of use
- Features can be placed in the UI itself
- Collaboration is possible
</div>

<div style="flex: 1; padding: 10px;">
### Cons
- Very basic visualization 
- Replicability issues
- Low data size limit (~1 MB)
</div>

</div>

### What is an API?

## Using Google Maps 
To get started, in Chrome navigate to:

**console.cloud.google.com**


Steps I did:
1. mapsplatform.google.com --> Maps Datasets --> Click 'API' button
2. 'Get started with google maps platform'
3. 'Create new project'
4. Name project 'NYC Open Data Crashes'
    - ID nyc-open-data-crashes
5. Left bar -> APIs & Services
    - Library
6. Maps JavaScript API
    - Enable
    - This brought me to an account info page
        - Payment info
7. Welcome Questions
    - Industry
    - What will you learn about
    - Development approach
    - What platforms
    - Framework
        -react 
    'Go to google maps platform'
8. 'Protect your API key'
    - Maybe later
9. Back to console.cloud page, skip any options
10. 

My first project:
API key: AIzaSyCW3MxADj1mC6V9fQxEiGngNJZytDXgr9c
NYC Open Data Crashes:
AIzaSyAfmyn2d8OzDSI10pJ-lnCbsexZmiLIwx0
